name: raccoon
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_snipit_test:
    name: raccoon test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && pip install --upgrade setuptools
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install raccoon
        run: pip3 install --break-system-packages -e .
      - name: Check raccoon version
        run: raccoon --version
      - name: Run raccoon with test data
        run: raccoon tests/test.fasta | tee raccoon.log


